### ISSUE TITLE
Update AMPL Ipopt executable

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [ampl/ampls-api#12]
I would like to use a new version of Ipopt with AMPL, precisely the newest one, 3.14.14. However, the file `ampl.linux64.tgz` gives me a folder with an Ipopt of version 3.12.3.

```sh
(base) user@pop-os:~/ampl/$ ./ipopt --version
Ipopt 3.12.13 (Linux x86_64), ASL(20221115)

(base) user@pop-os:~/$ ipopt --version # outside of folder ampl
Ipopt 3.14.14 (x86_64-pc-linux-gnu), ASL(20190605)
```

How can I force AMPL to use the new Ipopt version?

Thanks and regards.

**Comment by fdabrandao** [comment]
Hi @matheusdiogenesandrade,

You have a few options:
- Specify the full path to it: `option solver "/complete/path/to/ipopt"`
- Rename the ipopt executable inside the AMPL installation directory to avoid the conflict.

BTW, this repository is for our solver API with callbacks. For general AMPL support, there is a support forum: https://discuss.ampl.com/

**Comment by matheusdiogenesandrade** [comment]
> Hi @matheusdiogenesandrade,
> 
> You have a few options:
> 
> * Specify the full path to it: `option solver "/complete/path/to/ipopt"`
> * Rename the ipopt executable inside the AMPL installation directory to avoid the conflict.
> 
> BTW, this repository is for our solver API with callbacks. For general AMPL support, there is a support forum: https://discuss.ampl.com/

Thank you very much. The first option **worked just fine**. But, the second don't, even tried creating a symbolic link from my desired Ipopt version into the ampl folder, no success though.

Regards.

**Comment by fdabrandao** [comment]
Hi @matheusdiogenesandrade,

In the second option I meant renaming (or even deleting) the executable we include in the bundle to something else like `ipoptampl`. If the other `ipopt` executable is found in the environment variable PATH, then it would be used instead.

**Comment by matheusdiogenesandrade** [comment]
> Hi @matheusdiogenesandrade,
> 
> In the second option I meant renaming (or even deleting) the executable we include in the bundle to something else like `ipoptampl`. If the other `ipopt` executable is found in the environment variable PATH, then it would be used instead.

Thank you.
