### ISSUE TITLE
amplpy_gurobi callback variable names and amplpy variable names not matching.

### ISSUE THREAD

**Issue by RSchellenberger** [ampl/ampls-api#7]
Hello, this is less of a bug and more of a quality of life change...

When you create an amplpy.AMPL model and get get its amplpy.Variable variable instances, its var.name() field returns something of the like "x[(1, 1)]". However, when you export the model with amplpy.exportGurobiModel() and use .getSolutionDict() within a callback, it's keys will be "x[(1,1)]". It would be very convenient if these could be unified. 

I have attached a python file to demonstrate what I mean. 

[amplGurobiVarNameMismatch.py.txt](https://github.com/ampl/ampls-api/files/11422471/amplGurobiVarNameMismatch.py.txt)

I could do a string replace replacing ", " with ",", but then if my index includes a string that contains ', ', then it would break so its not a perfect solution. I know it may be difficult to change this if those strings are generated by gurobi itself, but if it isn't, then it would be great if these "names" could be unified so you could use them together more seemlessly

P.S. Also the file RuntimeError's for some reason and I'm not sure why. I didn't bother looking into that because it wasn't relevant to the point. I might have done something wrong to make that happen. If you happen to notice what was wrong, it would be good to know. Luckily, the file still demonstrates my point because it prints what it needs to before erroring

**Comment by fdabrandao** [comment]
amplpy v0.10.0 has just been released and the removal of the spaces in the indices is one of the changes.

```bash
$ python -m pip install "amplpy>=0.10.0" --upgrade
$ python amplGurobiVarNameMismatch.py
```

**Comment by fdabrandao** [comment]
amplpy v0.10.0 has just been released and the removal of the spaces in the indices is one of the changes. You can upgrade with: `python -m pip install "amplpy>=0.10.0" --upgrade`

```bash
$ python -m pip install "amplpy>=0.10.0" --upgrade
$ python amplGurobiVarNameMismatch.py
Var x with index (0,0)'s name is: x[0,0]
Gurobi 9.1.2: I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
I am wrong, whoops....
```

Regarding the `RuntimeError`, it was due to not having a return in the callback function:
```python
class myCallback(amplgb.GurobiCallback):
    def run(self):
        solutionDict = self.getSolutionDict()
        if firstVarName not in solutionDict.keys():
            print(
                firstVarName + " is not solution dict's keys Instead,"
                "  solution dict has keys of " + str(solutionDict.keys())
            )
        else:
            print("I am wrong, whoops....")
        return 0 # indicate that the solve process should continue 
```
