### ISSUE TITLE
Feasible Model -> Infeasible Model leads to a RunTimeError

### ISSUE THREAD

**Issue by RSchellenberger** [ampl/ampls-api#8]
Hello. If you do the following in a single python execution, you get a RunTimeError: Unknown exception
NOTE: I have ampl's presolve set to false because otherwise results in a different issue I plan to submit to amplpy's git. Additionally, this is a fully licensed environment with both an ampl license and a gurobi license set with the appropriate environment variables.
1. Create Feasible Model with amplpy
2. Export feasible model to amplpy_gurobi with .exportGurobiModel()
3. solve the feasible gurobi model
4.(Optional) import the solution back to amplpy with .importSolution() (this part isn't neccesary to make the bug happen)
5. Create an infeasible model with amplpy
6. Export the infeasible model to amplpy_gurobi with .exportGurobiModel() -> RuntimeError: Unknown Exception

I wonder if this has something to do with releasing the gurobi license, but that is just speculation based on the fact that the console will print out ampl license information and then say "No gurobi license for this machine." right before erroring (so the first, feasible model is able to find the gurobi license, but the second, infeasible is not). More detail is in the file below

Here is an example python file that replicates this behavior.

There is a similar bug around when you flip the order and do an infeasible model first but I will submit that as a separate issue because it results in a segmentation fault instead of a runtime error so it might be a different situation.

[amplGurobiFeasibleIntoInfeasibleRuntimeError.py.txt](https://github.com/ampl/ampls-api/files/11556389/amplGurobiFeasibleIntoInfeasibleRuntimeError.py.txt)

**Comment by fdabrandao** [comment]
Thanks for reporting this issue and for providing a reproducible example. We have just released amplpy-gurobi/ampl-cplex/amplpy-xpress v0.1 and this issue has been addressed:
```bash
$ python -m pip install amplpy_gurobi==0.1 --upgrade
$ python amplGurobiFeasibleIntoInfeasibleRuntimeError.py
Gurobi 10.0.1: optimal solution; objective 25
2 simplex iterations

Gurobi 10.0.1: optimal solution; objective 25
2 simplex iterations
Completed Simple Model Test.
Gurobi 10.0.1: infeasible problem
5 simplex iterations

Gurobi 10.0.1: infeasible problem
5 simplex iterations

suffix dunbdd OUT;
Completed Infeasible Model Test.
```
Please let us know if the problem persists or if any new issue arrises. This was a major update but we tried to keep backward compatibility with the previous version.

For infeasible models we now have the following `RuntimeError` exception:
```
RuntimeError: Could not find file: /var/folders/lc/kmnj4hgd7_qgjft0vlhjj0b40000gn/T/tmpjysvqrb0/model.nl, make sure it is exported from AMPL.
Note that if AMPL presolver detects an unfeasibility, it will not export it. To overcome this, set the
option 'presolve' to 0 before exporting the model.
```
