### ISSUE TITLE
Infeasible  Model -> Feasible Model leads to a Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by RSchellenberger** [ampl/ampls-api#9]
Hello. If you do the following in a single python execution, you get a Segmentation fault 
NOTE: I have ampl's presolve set to false because otherwise results in a different issue I plan to submit to amplpy's git. Additionally, this is a fully licensed environment with both an ampl license and a gurobi license set with the appropriate environment variables.
1. Create Infeasible Model with amplpy
2. Export infeasible model to amplpy_gurobi with .exportGurobiModel()
3. "solve" the infeasible gurobi model (and correctly get told it is infeasible)
4. (Optional) import the solution back to amplpy with .importSolution() (this part isn't necessary to make the bug happen)
5. Create a feasible model with amplpy
6. Export the feasible model to amplpy_gurobi with .exportGurobiModel() -> Segmentation Fault

Here is an example python file that replicates this behavior.

There is a similar bug around when you flip the order and do an feasible model first but I have submitted that as a separate issue because it results in a RuntimeError instead of a segmentation fault so it might be a different situation.

[amplGurobiInfeasibleIntoFeasibleSegFault.py.txt](https://github.com/ampl/ampls-api/files/11556446/amplGurobiInfeasibleIntoFeasibleSegFault.py.txt)

**Comment by fdabrandao** [comment]
Thanks for reporting this issue and for providing a reproducible example. We have just released amplpy-gurobi/ampl-cplex/amplpy-xpress v0.1 and this issue has been addressed:
```bash
$ python -m pip install amplpy_gurobi==0.1 --upgrade
$ python amplGurobiInfeasibleIntoFeasibleSegFault.py
Gurobi 10.0.1: infeasible problem
5 simplex iterations

Gurobi 10.0.1: infeasible problem
5 simplex iterations

suffix dunbdd OUT;
Completed Infeasible Model Test.
Gurobi 10.0.1: optimal solution; objective 25
2 simplex iterations

Gurobi 10.0.1: optimal solution; objective 25
2 simplex iterations
Completed Simple Model Test.
```
Please let us know if the problem persists or if any new issue arrises. This was a major update but we tried to keep backward compatibility with the previous version. 

For infeasible models we now have the following `RuntimeError` exception:
```
RuntimeError: Could not find file: /var/folders/lc/kmnj4hgd7_qgjft0vlhjj0b40000gn/T/tmpjysvqrb0/model.nl, make sure it is exported from AMPL.
Note that if AMPL presolver detects an unfeasibility, it will not export it. To overcome this, set the
option 'presolve' to 0 before exporting the model.
```
